drs_ids:
- a001
- a002
- a003
tes_uris:
  http://131.152.229.70/ga4gh/tes/v1/:
    currency: BTC
    unit_costs:
      cpu_usage: 1
      memory_consumption: 2
      data_storage: 3
      data_transfer: 4
  http://193.166.24.111/ga4gh/tes/v1/:
    currency: BTC
    unit_costs:
      cpu_usage: 4
      memory_consumption: 3
      data_storage: 2
      data_transfer: 1
drs_uris:
  http://131.152.229.71/ga4gh/drs/v1/:
  - id: a001
    name: file_1
    size: 16700000
    created: '2018-04-21T00:00:00-00:00'
    updated: '2018-08-08T16:00:00-05:00'
    version: '38'
    mime_type: application/json
    checksums:
    - checksum: ''
      type: None
    access_methods:
    - type: ftp
      access_url:
        url: https://www.nzz.ch/
        headers:
        - None
  - id: a002
    name: file_2
    size: 320000000
    created: '2015-04-21T00:25:43-06:00'
    updated: '2018-04-21T18:25:43-05:00'
    version: '1'
    mime_type: application/json
    checksums:
    - checksum: ''
      type: None
    access_methods:
    - type: ftp
      access_url:
        url: https://www.straitstimes.com/
        headers:
        - None
  - id: a003
    name: file_3
    size: 1000000000
    created: '2019-05-24T00:25:43-06:00'
    updated: '2019-07-08T00:00:00-00:00'
    version: ''
    mime_type: ''
    checksums:
    - checksum: None
      type: ''
    access_methods:
    - type: ftp
      access_url:
        url: https://www.bhaskar.com/
        headers:
        - None
  http://193.166.24.114/ga4gh/drs/v1/:
  - id: a001
    name: file_1
    size: 16700000
    created: '2018-04-21T00:00:00-00:00'
    updated: '2018-08-08T16:00:00-05:00'
    version: '38'
    mime_type: application/json
    checksums:
    - checksum: ''
      type: None
    access_methods:
    - type: ftp
      access_url:
        url: https://www.nzz.ch/
        headers:
        - None
  - id: a002
    name: file_2
    size: 320000000
    created: '2015-04-21T00:25:43-06:00'
    updated: '2018-04-21T18:25:43-05:00'
    version: '1'
    mime_type: application/json
    checksums:
    - checksum: ''
      type: None
    access_methods:
    - type: ftp
      access_url:
        url: https://www.nytimes.com/
        headers:
        - None
resource_requirements:
  cpu_cores: '2'
  execution_time_sec: '300'
  preemptible: true
  ram_gb: '8'
  disk_gb: '10'
  zones: []
mode: cost
auth_header: ''